config/routes.rb
Rails.application.routes.draw do
  get 'users/ranking'
  get 'questions/new'
  get 'questions/edit'
  root 'homes#top'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :questions, except: %i(show) do
    collection do
      get :search
      get :learning
    end
  end

  get 'users/ranking', to: 'users#ranking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  def self.search(search)
    if search.present?
      Question.where(['question LIKE ? OR description LIKE ?', "%#{ search }%", "%#{ search }%"])
    end
  end
end

app/models/question_similar.rb
class QuestionSimilar < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  def email_required?
    false
  end

  def self.ranking
    self.all.order(rate: 'DESC')
  end

  def my_rank(current_user)
    users = User.ranking
    @my_rank = 0
    users.each do |user|
      @my_rank += 1
      break if user.id == current_user.id
    end
    @my_rank
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller? 

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def top
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i(edit update destroy)

	def index
		@question = Question.new
		@questions = Question.all
	end

	def create
		@question = Question.new(question_params)
		if @question.save
			redirect_to questions_path(@question)
		else
			@questions = question.all
			render 'index'
		end
	end

  def edit
  end

  def update
		@question.update(question_params) ? (redirect_to questions_path) : (render 'edit')
  end

	def destroy
		@question.destroy
		redirect_to questions_path
  end

  def search
    @questions = Question.search(params[:search])
  end

	private

		def set_question
			@question = Question.find(params[:id])
		end

		def question_params
			params.require(:question).permit(:question, :description)
		end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def ranking
    @users = User.ranking
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.slim
.row
  .col-xs-3

  .col-xs-6
    .page-header
      h3
        | 単語帳アプリ

    = link_to '単語帳', learning_questions_path, class: 'btn btn-default btn-block'
    br
    = link_to 'ランキング', users_ranking_path, class: 'btn btn-default btn-block'
    br
    = link_to '単語メンテナンス', questions_path, class: 'btn btn-default btn-block'
    br
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-default btn-block'

  .col-xs-3

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | WordBook
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script src='https://kit.fontawesome.com/c51513dd6c.js' crossorigin='anonymous'
  body
    .container
      = yield

app/views/questions/_form.html.slim
= f.text_field :question, placeholder: '単語を入力してください', class: 'form-control'
br

= f.text_field :description, placeholder: '説明を入力してください', class: 'form-control'
br

app/views/questions/_questions.html.slim
.table-responsive
  table.table.table-bordered.table-hover
    thead
      tr.active
        th.text-center
          | ID
        th.text-center
          | 問題
        th.text-center
          | 説明
        th
        th

    tbody
      - questions.each do |question|
        tr
          td.text-center
            = question.id
          td.text-center
            = question.question
          td.text-center
            = question.description
          td.text-center
            = link_to '編集', edit_question_path(question), class: 'btn-sm btn-primary'
          td.text-center
            = link_to '削除', question_path(question), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn-sm btn-danger'

app/views/questions/_search_form.html.slim
  = form_with url: search_questions_path, method: :get, local: true do
    .col-xs-8
      = text_field_tag :search, '', placeholder: '単語検索', class: 'form-control'

    .col-xs-4
      = button_tag type: 'submit', name: nil, class: 'btn btn-info btn-block'
        i.fas.fa-search
        |  検索
      br

app/views/questions/edit.html.slim
.row
  .col-xs-3
  .col-xs-6

    .page-header
      h3
        | 単語編集

    = form_with model: @question, url: question_path(@question), local: true do |f|

      = render 'form', f: f

      = f.submit '保存', class: 'btn btn-success btn-block'
      br

  .col-xs-3

app/views/questions/index.html.slim
.row
  .page-header
    h3
      | 単語メンテナンス

.row
  .col-xs-4
    = form_with model: @question, url: questions_path(@question), local: true do |f|

      = render 'form', f: f

      = f.submit '登録', class: 'btn btn-success btn-block'
      br

    = link_to 'メニューへ戻る', root_path, class: 'btn btn-default'

  .col-xs-8
    .row
      = render 'search_form'
    .row
      = render 'questions', questions: @questions

app/views/questions/search.html.slim
.row
  .page-header
    h3
      | 単語検索

.row
  = render 'search_form'

.row
  = render 'questions', questions: @questions

.row
  = link_to 'メニューへ戻る', root_path, class: 'btn btn-default'

app/views/users/ranking.html.slim
.row
  .col-xs-3

  .col-xs-6
    .page-header
      h3
        | ユーザーランキング

    - if user_signed_in?
      |  あなたの順位は
      = @users.count
      | 人中
      strong
        = current_user.my_rank(current_user)
        | 位
      | です

    .table-responsive
      table.table.table-bordered.table-hover
        thead
          tr
            th.text-center
              | 順位
            th.text-center
              | 名前
            th.text-center
              | 正解率

        tbody
          - @users.each.with_index(1) do |user, index|
            tr
              td.text-center
                - case index when 1
                  i.fas.fa-crown[style='color: gold;']
                - when 2
                  i.fas.fa-crown[style='color: silver;']
                - when 3
                  i.fas.fa-crown[style='color: #B08A1C;']
                - else
                  = index
              td.text-center
                - if user == current_user
                  span style='color: red; font-weight: bold;'
                    = user.name
                - else
                  = user.name
              td.text-center
                - if user == current_user
                  span style='color: red; font-weight: bold;'
                    = user.rate
                    | %
                - else
                  = user.rate
                  | %

    = link_to 'メニューへ戻る', root_path, class: 'btn btn-default'

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
                count: resource.errors.count,
                resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "ログイン", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "新規ユーザー作成", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "パスワードを忘れた方はこちら", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br